services:
  postgres:
    image: postgres:latest
    container_name: odoo_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: protick1234
      POSTGRES_DB: odoo_hr_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - odoo_network

  odoo:
    image: odoo:latest
    container_name: odoo_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo123
      - POSTGRES_DB=odoo_hr_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/extra-addons
    # Remove the problematic command and let Odoo use the config file
    networks:
      - odoo_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: odoo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: AdminPass123
    ports:
      - "3000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - odoo_network

volumes:
  pgdata:
  pgadmin-data:
  odoo-web-data:

networks:
  odoo_network:
    driver: bridge
    name: odoo_network
